/**
 * Cover derivatives, generated by hand rather than by the build.
 *
 * The masters live in `assets/covers/<stream>/<slug>.png`: full-resolution
 * captures, ~3MB each, deliberately outside `public/` and outside git. This
 * script turns each one into the three sizes the page actually requests and the
 * OG card the crawlers fetch, and those derivatives *are* committed.
 *
 * It is not part of `npm run build` on purpose. `sharp` is a platform-specific
 * binary that is not in `package.json`, the masters are not in the repo, and the
 * output changes only when a post is added, and a build step that needs two things
 * a fresh clone doesn't have is a build step that breaks CI on day one. Run it
 * when covers change:
 *
 *     npm i -D sharp && npm run covers
 *
 * Every published post must have a master. A missing one throws here rather
 * than shipping a page with a broken hero, the same bargain
 * `generate-banners.mjs` makes with the plate.
 */
import { existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { collect, pathOf, root } from './lib/content.mjs';

const SRC = join(root, 'assets', 'covers');
const COVERS = join(root, 'public', 'covers');
const OG = join(root, 'public', 'og');

/**
 * The widths the hero and the feed thumbnail ask for.
 *
 * 1600 is the widest the band is ever painted (a full-bleed 2:1 strip on a
 * desktop viewport); 480 is the feed thumbnail on mobile. 800 is the middle the
 * browser picks on a phone at 2x, which is most of the traffic.
 */
const WIDTHS = [1600, 800, 480];

/** Facebook and X both crop to this. Every master is already within 1% of it. */
const OG_SIZE = { width: 1200, height: 630 };

/**
 * The masters are browser captures, so the outermost pixels are the page's own
 * chrome, a hairline of near-black along the top and sides. Four pixels off
 * each edge removes it without touching the composition.
 */
const INSET = 4;

let sharp;
try {
  ({ default: sharp } = await import('sharp'));
} catch {
  console.error('[covers] sharp is not installed. `npm i -D sharp` and run this again.');
  process.exit(1);
}

const posts = collect();
if (!posts.length) {
  console.log('[covers] no published posts, nothing to render.');
  process.exit(0);
}

let written = 0;
for (const post of posts) {
  // `cover: false` posts ship without a cover or OG card by design; see
  // `hasCover` in src/data/notes.ts.
  if (post.cover === false) continue;
  const path = pathOf(post);
  const master = join(SRC, post.dir, `${post.slug}.png`);
  if (!existsSync(master)) {
    throw new Error(`covers: ${path} has no master at assets/covers/${post.dir}/${post.slug}.png`);
  }

  const { width, height } = await sharp(master).metadata();

  const region = () => ({
    left: INSET,
    top: INSET,
    width: width - INSET * 2,
    height: height - INSET * 2,
  });

  const trimmed = () => sharp(master).extract(region());

  mkdirSync(join(COVERS, post.dir), { recursive: true });
  for (const w of WIDTHS) {
    const out = join(COVERS, post.dir, `${post.slug}-${w}.webp`);
    // Width only. The band is painted with `aspect-ratio` and `object-fit:
    // cover`, so the height is free to fall out of the source, and every master
    // is already within a percent of 2:1.
    const info = await trimmed().resize({ width: w }).webp({ quality: 74, effort: 6 }).toFile(out);
    written += 1;
    if (w === WIDTHS[0]) {
      console.log(`[covers] public/covers${path}-${w}.webp  ${info.width}x${info.height}  ${(info.size / 1024).toFixed(0)}KB`);
    }
  }

  mkdirSync(join(OG, post.dir), { recursive: true });
  const card = await trimmed()
    .resize({ ...OG_SIZE, fit: 'cover' })
    // JPEG, not PNG: the old cards were flat colour and quantised to 40KB, these
    // are photographs and would be ten times that as PNG. `mozjpeg` holds the
    // burnt-in title crisp at a quality where the artwork is still small.
    .jpeg({ quality: 82, mozjpeg: true })
    .toFile(join(OG, post.dir, `${post.slug}.jpg`));
  written += 1;
  console.log(`[covers] public/og${path}.jpg  ${(card.size / 1024).toFixed(0)}KB`);
}

console.log(`[covers] ${written} file${written === 1 ? '' : 's'} written for ${posts.length} posts.`);
